version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    networks:
      - mynetwork
      
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

volumes:
  data:

